### ISSUE TITLE
Notice: Undefined property: 

### ISSUE THREAD

**Issue by PGLDK** [bambora/checkout-magento-v2.x#10]
Der lader til at være et problem hvis du af en grund hæver beløbet i din Epay gateway, FØR ordren er faktureret i M2. Ex hvis beløbet skal tilrettes.

Transaction står ordren som closed: no, det betyder at ordren står og hænger som processing, selvom ordren er faktureret og afsendt.

Når du forsøger at gå til fakturaen og laver en fiktiv-capture ved at trykke på capture, for at lukke ordren i M2 fremkommer følgende fejl:
Notice: Undefined property:  Bambora\Online\Model\Api\Epay\Response\Capture::$epayresponse in /var/www/***SHOPNAVN***/public_html/vendor/bambora/module-payment-magento2/Helper/Data.php on line 450
Invoice capturing error

**Comment by AllanWLie** [comment]
Hej @PGLDK 
Fejlen som du oplever burde være fikset i den nyeste release.
https://github.com/bambora/bambora-online-magento-v2.x/releases/latest

-Allan
