### ISSUE TITLE
Icons and slow loading

### ISSUE THREAD

**Issue by PGLDK** [bambora/checkout-magento-v2.x#11]
![epay_icons](https://cloud.githubusercontent.com/assets/22352667/23788024/fcee6380-0574-11e7-839c-72a61bbc18a9.png)

There seems to be a problem with the payment icons and how they are served. The icons is often being loaded very slow externally. What about making it possible to store them local instead of extern?

**Comment by AllanWLie** [comment]
Hi @PGLDK 

We will look into this in a future release.

**Comment by AllanWLie** [comment]
You can try to change rows=2 to rows=1 on this line
https://github.com/bambora/bambora-online-magento-v2.x/blob/master/Model/Api/Epay/Action.php#L83

**Comment by PGLDK** [comment]
Did the trick :-)
