### ISSUE TITLE
Critical issue when canceling payment.

### ISSUE THREAD

**Issue by PGLDK** [bambora/checkout-magento-v2.x#12]
A very urgent and critical issue closed by Magento (not a Magento issue)

Read more here: https://github.com/magento/magento2/issues/8843

**Comment by AllanWLie** [comment]
Hi @PGLDK 

We do not have a solution for this issue, but we are working on it. 
If you have a solution, then you are very welcome to make a pull request.

**Comment by spiilmusic** [comment]
Any news here?
