### ISSUE TITLE
Error on free orders

### ISSUE THREAD

**Issue by giano574** [bambora/checkout-magento-v2.x#16]
I get the following error when completing an order with a grand total of 0:
`Bambora.ERROR: Bambora ePay Error - ID:  - Callback Failed: The Payment object is null [] []`
Everything does seem to work normally though.

**Comment by giano574** [comment]
This also happens sometimes with paid orders.

**Comment by giano574** [comment]
Actually it seems to happen on orders where a coupon code is used

**Comment by AllanWLie** [comment]
Hi @giano574 

In Magento 2 you should not be able to chose a payment method if the Grand total is 0.
