### ISSUE TITLE
epay: Variable undefined in strict mode

### ISSUE THREAD

**Issue by Doehl** [bambora/checkout-magento-v2.x#17]
We have just updated to V1.2.0, and do now have a problem in IE 11.
When we click "place order", do we see the following error in the IE 11 Console: **Variable undefined in strict mode**. The error is thrown on the following line.
https://github.com/bambora/bambora-online-magento-v2.x/blob/master/view/frontend/web/js/view/payment/method-renderer/bambora-epay-method.js#L34 

**Magento Version: 2.1.6**

**Comment by Doehl** [comment]
IE11 do not in `strict mode` allow assignment of read-only variable.

**Comment by asixseight** [comment]
We are experiencing the same problem currently.
All the property assignments of `self` are assigned incorrectly in strict mode as `self` is never defined prior to this.
Simply prefixing the assignments with `var` would solve this problem.

**Comment by AllanWLie** [comment]
Hi all, 
Thank you for the feedback, we will correct this in the next release.

Best regards
Allan Lie

**Comment by AllanWLie** [comment]
Hi,

This have now been fixed see the latest release: https://github.com/bambora/checkout-magento-v2.x/releases/latest
