### ISSUE TITLE
Broken in magento2 produciton mode ( 2.1.1 ) /w JS minification enabled.

### ISSUE THREAD

**Issue by peec** [bambora/checkout-magento-v2.x#2]
Bambora online v. 1.1.0:

**Environement:**
Magento 2.1.1
Production mode enabled
All magento-production settings enabled: Html minification, JS minification, JS bundle, CSS minification etc.

**Relevant logs:**

From system.log ( don't know if its relevant ):

2016-10-10 20:21:57] main.CRITICAL: Broken reference: No element found with ID 'checkout.header.wrapper'. [] []

From bambora.log

[2016-10-10 20:22:46] Bambora.ERROR: ID: 000000003 -  [] []

![image](https://cloud.githubusercontent.com/assets/131546/19249977/66fae360-8f38-11e6-8c3f-bc0350bc65e5.png)

**Comment by peec** [comment]
Minification and JS bundling enabled. Html minification enabled. Seems like some error in the JS / not compatible to be minified.

![image](https://cloud.githubusercontent.com/assets/131546/19250180/4affe10a-8f39-11e6-8761-0141a5c5aa88.png)

This is the source of error:

```
(function() {
ï»¿define(['uiComponent','Magento_Checkout/js/model/payment/renderer-list'],function(Component,rendererList){'use strict';rendererList.push({type:'bambora_checkout',component:'Bambora_Online/js/view/payment/method-renderer/bambora-checkout-method'},{type:'bambora_epay',component:'Bambora_Online/js/view/payment/method-renderer/bambora-epay-method'});return Component.extend({});});
})
```

Can it be the bambora ascii that destroys minifcation?

**Comment by peec** [comment]
@AllanWLie See http://stackoverflow.com/questions/3255993/how-do-i-remove-%C3%AF-from-the-beginning-of-a-file

**Comment by AllanWLie** [comment]
Hi peec,

Thank you for posting this issue.

We will look into it and return to you

-Allan

**Comment by AllanWLie** [comment]
Hi again,

We have now fixed the issue and created a new release.

https://github.com/bambora/bambora-online-magento-v2.x/releases/latest
