### ISSUE TITLE
Stuck with pending orders if browser is closed when when payment window is open

### ISSUE THREAD

**Issue by mysil2** [bambora/checkout-magento-v2.x#26]
Orders seems to be created when initiating the payment window and cancelled if the user clicks "cancel". However, if the user just exits the browser without paying, the order is stuck in pending state.

Possible features to change this:
1. Option to not create the order before the payment is completed. I can see this could lead to error in the order if the stock has changed in the timeframe between initiating and completion of the payment.
2. Creating a cron job checking pending orders paid by the Bambora option and cancels the orders that have timed out.

**Comment by AllanWLie** [comment]
Hi @mysil2 

Thank you for reporting this issue. We will look into the issue and a fix might be added to a future release.

Best regards 
Allan - Bambora
