### ISSUE TITLE
Multi website 

### ISSUE THREAD

**Issue by christianlknudsen** [bambora/checkout-magento-v2.x#28]
Hi there is a known bug in your extension when running multi website with different merchant numbers. The capture function from backend is not working. You send earlier a fix for this see below. It would be great if that would be released in future versions.

Denne https://github.com/bambora/checkout-magento-v2.x/blob/master/Model/Method/Epay/Payment.php#L52

 Change to:

 
public function getAuth($storeId = null)

{

   if (!$this->_auth) {

      if($storeId == null) {

         $storeId = $this->getStoreManager()->getStore()->getId();

      }

      $this->_auth = $this->_bamboraHelper->generateEpayAuth($storeId);

   }

   return $this->_auth;

}

 This line

https://github.com/bambora/checkout-magento-v2.x/blob/master/Model/Method/Epay/Payment.php#L288

And this

https://github.com/bambora/checkout-magento-v2.x/blob/master/Model/Method/Epay/Payment.php#L291

 change to 

$this->getAuth()

til

$this->getAuth($order->getStoreId())

**Comment by AllanWLie** [comment]
Hi @christianlknudsen 

The issue have been fixed in the newest release: https://github.com/bambora/checkout-magento-v2.x/releases/latest

Have a great day

Best regards
Allan - Bambora
