### ISSUE TITLE
[v1.1.2] Error after selecting bambora as payment method and submit

### ISSUE THREAD

**Issue by peec** [bambora/checkout-magento-v2.x#3]
Thanks for fixing the previous issue.

Now I have another issue, which may be because some kind of validation towards the URL we use for our test site.

After selecting bambora as payment method and submiting the payment you get redirected to the Checkout page.

I think its because the format of our dev-url is like:  `yyyyy-xxxx-dev.xxxxxxx.eu-west-1.elasticbeanstalk.com/checkout/cart/` (subdomains). Unfortunately we can't change these urls, they are like this for all our sites that has not yet reached production. When they finally get a normal domain like yyy.com

I tried adding all permissions in Bambora backoffice, but that didn't work.

**Logs:**

```
[2016-10-13 12:17:13] Bambora.ERROR: Bambora Checkout Error - ID: 000000027 -  [] []
[2016-10-13 12:17:13] Bambora.INFO: Bambora Checkout Info - ID: 000000027 - The order was canceled [] []
```

![image](https://cloud.githubusercontent.com/assets/131546/19348690/7300e7c2-914f-11e6-970c-a7bf42e01d69.png)

![image](https://cloud.githubusercontent.com/assets/131546/19348588/f456187a-914e-11e6-8787-1c2192f2eb17.png)

**Comment by AllanWLie** [comment]
Hi again,

We accept all sub-domains based on the domain you registered when signing up for a Bambora Checkout account.

If you want further support for your domains or registration please write an email to support@bambora.com and provide your merchant number and issue then we can help you with your account configuration.

Thank you

Kind regards
Allan
