### ISSUE TITLE
Dot placement in onestepcheckout

### ISSUE THREAD

**Issue by Thearcangelo** [bambora/checkout-magento-v2.x#35]
![image001](https://user-images.githubusercontent.com/34103615/72983499-b6153300-3de1-11ea-93df-1aeeb17e1778.png)

I can not style the button in the checkout page with css.
And it looks stupid that everything else in magento be default have the button next the the paymentoption - and bambora dot is next to the text.

**Comment by AllanWLie** [comment]
Hi @Thearcangelo 

Thank you for your input, but it is not something we are going to change. 

Have a good day.

Best regard
Allan - Bambora Online A/S
