### ISSUE TITLE
Missing support for Magento 2.4 and PHP 7.3

### ISSUE THREAD

**Issue by HansiBlomberg** [bambora/checkout-magento-v2.x#38]
"PCI DSS requirement 6.1 states merchants must “deploy critical patches within a month of release” to maintain compliance."

To keep ahead with what is expected of me as a Merchant, I am planning to upgrade to Magento 2.4 to not fall behind.

But, ironically, my Payment module is not compatible with the new version, because new minimum PHP version is 7.3.

bambora/module-payment-magento2 2.0.2 requires php ~5.5.22|~5.6.0|7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.20) does not satisfy that requirement.

https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html
PHP 7.4 support introduced and PHP 7.1 and 7.2 deprecated. Magento 2.4.0 introduces support for PHP 7.4.

**Comment by DrKoolaid** [comment]
Any progress on this ?

**Comment by puntable** [comment]
You need to update composer requirements. I created a PR but they did not accept it for some reason.
You can update composer requirements yourself to get it working.

`/vendor/bambora/module-payment-magento2/composer.json`

Update require section from:
```
"require": {
    "magento/framework": "100.* | 101.* | 102.*",
    "magento/module-backend": "100.* | 101.*",
    "magento/module-catalog": "100.* | 101.* | 102.* | 103.*",
    "magento/module-checkout": "100.*",
    "magento/module-config": "100.* | 101.*",
    "magento/module-payment": "100.*",
    "magento/module-quote": "100.* | 101.*",
    "magento/module-sales": "100.* | 101.* | 102.*",
    "magento/module-store": "100.* | 101.*",
    "magento/module-tax": "100.*",
    "magento/module-ui": "100.* | 101.*",
    "zendframework/zend-soap": "^2.4.6"
  },
```
to
```
  "require": {
    "magento/framework": "100.* | 101.* | 102.* | 103.*",
    "magento/module-backend": "100.* | 101.* | 102.*",
    "magento/module-catalog": "100.* | 101.* | 102.* | 103.* | 104.*",
    "magento/module-checkout": "100.*",
    "magento/module-config": "100.* | 101.*",
    "magento/module-payment": "100.*",
    "magento/module-quote": "100.* | 101.*",
    "magento/module-sales": "100.* | 101.* | 102.* | 103.*",
    "magento/module-store": "100.* | 101.*",
    "magento/module-tax": "100.*",
    "magento/module-ui": "100.* | 101.*",
    "zendframework/zend-soap": "^2.4.6"
  },
```

Tested and working fine with 2.4

**Comment by AllanWLie** [comment]
Thank you @puntable for publishing the updated Composer.Json file. 
The changes for 2.4 comparability is now released.

Module version 2.2.1

Best regards
Allan Lie - Bambora Online A/S
