### ISSUE TITLE
Bekræft handelsbetingelser virker ikke med epay modulet

### ISSUE THREAD

**Issue by langhoff28** [bambora/checkout-magento-v2.x#4]
I magento2 bekræftes handelsvilkår i hver betalingsform. Se eksempel her ved check / money order http://www.awesomescreenshot.com/image/1759698/a89a839a0137afe417113c913677dfa2

Hvis man vælger epay kommer tick boksen ikke frem se her http://www.awesomescreenshot.com/image/1759712/ee1a98e8d75f4aacc61451a96006875f

Vi har testet paypal, braintree, bankoverførelse og det vises på alle med undtagelse af epay modulet :-)

**Comment by AllanWLie** [comment]
@langhoff28 Tak for din tilbagemelding. Det er blevet implementeret, og kommer med i næste release af modulet.

**Comment by AllanWLie** [comment]
@langhoff28 Så har vi frigivet en ny version af modulet, som blandt andet indeholder "Terms and Conditions" på checkout siden.

Link: https://github.com/bambora/bambora-online-magento-v2.x/releases/latest
