### ISSUE TITLE
How to allow save credit card on checkout 

### ISSUE THREAD

**Issue by jesperbrejning** [bambora/checkout-magento-v2.x#40]
Bambara Checkout gives an option to save your credit card. 

It looks like the following is missing in the M2 module to make this work. How can we implement this in the module? 

Best regards, 
Jesper 

Enable Paying with a Saved Card
In order to enable purchase with a saved card in Checkout, the customer object has to be included in the create session reques.

{
  "customer": {
    "phonenumbercountrycode": "45",
    "phonenumber": "12345678",
    "email": "john.doe@example.com"
  }
}

**Comment by jesperbrejning** [comment]
More info about "save card in checkout"

https://developer.bambora.com/europe/checkout/guides/save-card-in-checkout

**Comment by AllanWLie** [comment]
Hi @jesperbrejning 
The feature for saving your credit card is disabled due to the new PSD2 regulations. The page you are referring to, is only visible if you know the url. 

Have a good day.
