### ISSUE TITLE
Bambora Delete - Salable Quantity / Quantity bug

### ISSUE THREAD

**Issue by kasperth** [bambora/checkout-magento-v2.x#42]
Using the mass action "Bambora delete" results in the marked orders being deleted.
The issue is, that the products sold and deduceted from the "Salable Quantity" is not refunded when the order is "Bambora deleted". This results in a guaranteed mismatch between Quantity and Salable Quantity, which will cause big issues for the quantity and stock handling.

I see 2 ways of solving this issue.

1. Removing the "Bambora delete" mass action from the module.
2. Using the mass action, the products should be refunded to stock before the entire order is deleted. So basically cancel the order using standard M2 standard and then delete afterwards.

**Comment by mortenbirkelund** [comment]
@AllanWLie Any inputs?

**Comment by sessan** [comment]
This has now been prioritised and we will remove the "Bambora delete"-mass action from the module.

**Comment by sessan** [comment]
In the latest release the mass action "Bambora delete" is removed from the module. @kasperth @mortenbirkelund 
Best Regards
Jessica Björkäng
Developer Bambora Online
