### ISSUE TITLE
splitpayment option is missing

### ISSUE THREAD

**Issue by jtwogw** [bambora/checkout-magento-v2.x#43]
Would you add option splitpayment for the Nets/Teller as acquirer? 
It is not possible to capture multiple times without this option for Nets.

**Comment by sessan** [comment]
Hello! @jtwogw 
No, we will not. Cause for splitpayment for nets, there will be done a 0 auth and a full auth when the first capture is done, but then it can be that the money isn't available. If you have more questions regarding this please contact support. Best Regards 
Jessica, Open Source Developer Bambora Online
