### ISSUE TITLE
Support for Magento 2.4.4 and PHP 8.1

### ISSUE THREAD

**Issue by puntable** [bambora/checkout-magento-v2.x#45]
Hi,

What is the status of getting this module updated to be compatible with 2.4.4 and PHP 8.1? 
I see issues with `zendframework/zend-soap` which need to be replaced `laminas/laminas-soap` and some "Deprecated Functionality" warnings.

**Comment by sessan** [comment]
Unfortunately Adobe introduced these breaking changes in a patch release, hence we cannot just upgrade without making sure that the module is backwards compatible, but we are working on it.

**Comment by christianlknudsen** [comment]
unsubscribe

**Comment by sessan** [comment]
New version 2.4.0 is now available but awaiting Magentos QA. @puntable

**Comment by puntable** [comment]
Can you please update Packagist. Version stuck at 2.3.7.

**Comment by sessan** [comment]
@puntable It usually updates automatically but now its published there as well.
