### ISSUE TITLE
unable to integerate it in IFRAME

### ISSUE THREAD

**Issue by zeeshan2523806** [bambora/checkout-magento-v2.x#5]
Hi Guyz,

Thank you so much for this wonderfull work, i will be needing a small assistance in this regard.

I am using this extension to integerate Epay Payment method for my client, i am using porto theme on magento2.1. on checkout page when we click for pay with epay it redirect to the epay website, and ask for the payment over there, i want to integerate it into my own website so that user do not need to go to the epay website,

Please let me know how we can use window state id 2 for this extension so that the payment form and processing can be done on my website.

Thank you

**Comment by AllanWLie** [comment]
@zeeshan2523806 
Hi, 
Thank you for using our module.

We do not have a solution for the Iframe option for this module and right now it is not in our roadmap.

You are always welcome to make a pull request and create an integration for this option.

Have a nice day

Kind regards
Allan
