### ISSUE TITLE
Missing currency in callback

### ISSUE THREAD

**Issue by puntable** [bambora/checkout-magento-v2.x#50]
> Magento 2.4.5
> PHP 8.1

Callback is failing because of missing currency in the post request.
See line [65](https://github.com/bambora/checkout-magento-v2.x/blob/master/Controller/Epay/Callback.php#L65) in Callback controller. This data is not available in the callback (atleast for one of my customers).

This is what that callback looks like:
`https://www.webshop.dk/bambora/epay/callback/?txnid=123456789&orderid=M20004621&amount=811875¤cy=208&date=20220824&time=1403&txnfee=0&paymenttype=1&cardno=457124XXXXXX3240&hash=f45bf670c06f12345a5aa96346ff250`

It looks like an error in the callback. Specifically `¤cy=208`, which should be `currency=208`.
Perhaps you should forward this error to the people resonsible for the callbacks.

**Comment by sessan** [comment]
Hi @puntable 

The callback-link shown in the admin of ePay unfortunately decodes the **&curren** argument to **¤**. This has nothing to do with the callback sent from the server but only how it is shown in admin. 

Best Regards
Jessica, Bambora Online
